config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'lists#index'

  resources :lists, except: [ :edit, :update ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :overview, presence: true
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]
  

  def new
    @bookmark = Bookmark.new
  end


  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    # flash[:notice] = @bookmark.errors.full_messages.to_sentence unless @bookmark.save
    # redirect_to list_path(@list)
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :set_list, only: [ :show, :destroy ]
# has_one_attached :photo

  def index
    @lists = List.all
  end

  def show
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def new
    @list = List.new
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h3>Add a movie to your <%= @list.name %> list</h3>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
  <%= f.association :movie, prompt: 'Select a movie', input_html: { class: 'select2' } %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
        <%= f.input :name, placeholder: 'Drama' %>
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<table>
  <tbody>
    <% lists.each do |list| %>
      <tr>
        <td><%= link_to list.name, list_path(list) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-black">
    <h1>Save any kind of movies</h1>
    <h3 class="typed-js"></h3>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0" data-controller="typed-js">My Lists</h3>
    <%= link_to 'Create a movie list', new_list_path, class: 'btn btn-primary' %>
  </div>
</div>

<div class="row">
    <% @lists.each do |list| %>
      <div class="co-12 colsm-6 col-md-4">
        <%= link_to list_path(list), class:'text-decoration-none' do %>
          <%# <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path('list_background.jpg') %>
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ul class="list-group">
    <% @list.bookmarks.each do |bookmark| %>
    <li class="list-group-item"><%= bookmark.movie.title %> - <%= bookmark.comment %> <%= link_to "Remove",
                  bookmark_path(bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  <% end %>

<%=link_to "add new movie", new_list_bookmark_path(@list)%>
<%=link_to "See lists", lists_path%>